import { useBlockProps } from '@wordpress/block-editor';

export default function save({ attributes }) {
  const {
    images = [],
    columns = 3,
    gap = 16,
    showCaptions = true,
    imageSize = 'full',
    customWidth = 0,
    customHeight = 0,
    layoutType = 'grid',
    showPagination = false,
    itemsPerPage = 12,

   //Grid layout 
    gridBackgroundColor = '#000000',
    grindCaptionColor = '#ffffff',
    GtBgap = 0,

    // Lightbox specific attributes
    LightBackgroundColor = '#000000',
    LightCaptionColor = '#ffffff',
    LighttBgap = 0,

    // Image Browser attributes
    browserShowThumbnails = true,
    browserShowNavigation = true,
    browserShowCounter = true,
    browserAutoFullscreen = false,
    browserZoomEnabled = true,
    ImgbackgroundColor = '#000000',
    ImgCaptionColor = '#ffffff',

    // Masonry specific attributes
    masonryBorderRadius = 8,
    masonryImageBorder = 0,
    masonryImageBorderColor = '#e0e0e0',
    masonryImageBorderStyle = 'solid',

    // Infinite Carousel attributes
    alignx='center',
    imagepadding= 2,
    animationSpeed= 25,

     // swiper Carousel attributes
    swiperautoplay = true,
    autoplayDelay = 500,


  } = attributes;

  // If no images, render empty div to maintain consistency
  if (images.length === 0) {
    return (
      <div {...useBlockProps.save({ className: 'my-gallery' })}>
        <div className="my-gallery__empty">
          {/* Empty state - no images */}
        </div>
      </div>
    );
  }

  const blockProps = useBlockProps.save({
    className: 'my-gallery',
  });

  if (layoutType === 'grid') {
    return (
      <div {...blockProps}>
        <div
          className="my-gallery__grid"
          style={{ 
            '--columns': columns, 
            '--gap': `${gap}px`,
            display: 'grid',
            gridTemplateColumns: `repeat(${columns}, 1fr)`,
            gap: `${gap}px`
          }}
          data-bg-color={gridBackgroundColor}
          data-caption-color={grindCaptionColor}
          data-columns={columns}
          data-gap={gap}
          data-show-pagination={showPagination ? 'true' : 'false'}
          data-items-per-page={itemsPerPage}
        >
          {images.map((img, index) => {
            const imageUrl = imageSize === 'custom' 
              ? img.url 
              : (img.sizes && img.sizes[imageSize] && img.sizes[imageSize].url) || img.url;
            
            const imageStyles = imageSize === 'custom' && (customWidth || customHeight) 
              ? {
                  width: customWidth ? `${customWidth}px` : 'auto',
                  height: customHeight ? `${customHeight}px` : 'auto',
                }
              : {};

            return (
              <figure 
                key={img.id || index} 
                className="wpc-gallery__item"
                data-image-id={img.id || index}
              >
                <img
                  src={imageUrl}
                  alt={img.alt || ''}
                  style={Object.keys(imageStyles).length > 0 ? imageStyles : undefined}
                />
                 {showCaptions && img.caption && (
                      <figcaption style={{ 
                            backgroundColor: gridBackgroundColor, 
                            color: grindCaptionColor,
                            paddingTop:GtBgap,
                            paddingBottom:GtBgap }}> {img.caption} </figcaption>
                )}
              </figure>
            );
          })}
        </div>

        {showPagination && images.length > itemsPerPage && (
          <div 
            className="my-gallery__pagination"
            data-total-items={images.length}
            data-items-per-page={itemsPerPage}
          >
            {/* Pagination will be generated by JavaScript */}
          </div>
        )}
      </div>
    );
    
  } else if (layoutType === 'lightbox') {
    return (
      <div {...blockProps}>
        <div
          className="my-gallery__lightbox-grid"
          style={{ 
            '--columns': columns, 
            '--gap': `${gap}px`,
            display: 'grid',
            gridTemplateColumns: `repeat(${columns}, 1fr)`,
            gap: `${gap}px`,
           
          }}
          data-layout="lightbox"
          data-columns={columns}
          data-gap={gap}
          data-show-captions={showCaptions ? 'true' : 'false'}
          data-show-pagination={showPagination ? 'true' : 'false'}
          data-items-per-page={itemsPerPage}
          data-total-items={images.length}
        >
          {images.map((img, index) => {
            const imageUrl = imageSize === 'custom' 
              ? img.url 
              : (img.sizes && img.sizes[imageSize] && img.sizes[imageSize].url) || img.url;
            
            const fullImageUrl = img.sizes && img.sizes['full'] && img.sizes['full'].url 
              ? img.sizes['full'].url 
              : img.url;
            
            const imageStyles = imageSize === 'custom' && (customWidth || customHeight) 
              ? {
                  width: customWidth ? `${customWidth}px` : 'auto',
                  height: customHeight ? `${customHeight}px` : 'auto',
                }
              : {};

            return (
              <figure 
                  key={img.id || index} 
                  className="my-gallery__lightbox-item"
                  data-image-id={img.id || index}
                  data-image-index={index}
                  data-full-image={fullImageUrl}
                  data-caption={img.caption || ''}
                  data-alt={img.alt || ''}
                >
                  <div className="my-gallery__lightbox-thumb">
                    <img src={imageUrl} alt={img.alt || ''} style={Object.keys(imageStyles).length > 0 ? imageStyles : undefined}
                    />
                    <div className="my-gallery__lightbox-overlay">
                      <span className="my-gallery__lightbox-icon">🔍</span>
                    </div>
                  </div>
                  {showCaptions && img.caption && (
                    
                     <figcaption style={{ 
                            backgroundColor: LightBackgroundColor, 
                            color: LightCaptionColor,
                            paddingTop:LighttBgap,
                            paddingBottom:LighttBgap }}> {img.caption} </figcaption>
                  )}
              </figure>
            );
          })}
        </div>

        {showPagination && images.length > itemsPerPage && (
          <div className="my-gallery__pagination" data-total-items={images.length} data-items-per-page={itemsPerPage} >
            {/* Pagination will be generated by JavaScript */}
          </div>
        )}

        {/* Lightbox Modal Structure */}
        <div className="my-gallery__lightbox-modal" style={{ display: 'none' }}>
          <div className="my-gallery__lightbox-backdrop"></div>
          <div className="my-gallery__lightbox-container">
            <button className="my-gallery__lightbox-close" aria-label="Close lightbox">×</button>
            <button className="my-gallery__lightbox-prev" aria-label="Previous image">❮</button>
            <button className="my-gallery__lightbox-next" aria-label="Next image">❯</button>
            <div className="my-gallery__lightbox-content">
              <img className="my-gallery__lightbox-image" src="" alt="" />
              <div className="my-gallery__lightbox-caption"></div>
            </div>
          </div>
        </div>
      </div>
    );
  } else if (layoutType === 'imagebrowser') {
    return (
      <div {...blockProps}>
        <div
          className="my-gallery__imagebrowser"
          data-layout="imagebrowser"
          data-bg-color={ImgbackgroundColor}
          data-caption-color={ImgCaptionColor}
          data-show-thumbnails={browserShowThumbnails ? 'true' : 'false'}
          data-show-navigation={browserShowNavigation ? 'true' : 'false'}
          data-show-counter={browserShowCounter ? 'true' : 'false'}
          data-auto-fullscreen={browserAutoFullscreen ? 'true' : 'false'}
          data-zoom-enabled={browserZoomEnabled ? 'true' : 'false'}
          data-show-captions={showCaptions ? 'true' : 'false'}
          data-total-images={images.length}
          data-transition-effect="fade"
        >
          {/* Image Browser Main Container */}
          <div className="my-gallery__imagebrowser-main">
            <div className="my-gallery__imagebrowser-viewer">
              {images.map((img, index) => {
                const imageUrl = imageSize === 'custom' 
                  ? img.url 
                  : (img.sizes && img.sizes[imageSize] && img.sizes[imageSize].url) || img.url;
                
                const fullImageUrl = img.sizes && img.sizes['full'] && img.sizes['full'].url 
                  ? img.sizes['full'].url 
                  : img.url;
                
                const imageStyles = imageSize === 'custom' && (customWidth || customHeight) 
                  ? {
                      width: customWidth ? `${customWidth}px` : 'auto',
                      height: customHeight ? `${customHeight}px` : 'auto',
                    }
                  : {};

                return (
                  <div 
                    key={img.id || index} 
                    className={`my-gallery__browser-image ${index === 0 ? 'active' : ''}`}
                    data-image-index={index}
                    data-image-id={img.id || index}
                    data-full-image={fullImageUrl}
                    data-alt={img.alt || ''}
                    data-caption={img.caption || ''}
                  >
                    <img
                      src={imageUrl}
                      alt={img.alt || ''}
                      style={Object.keys(imageStyles).length > 0 ? imageStyles : undefined}
                      data-zoom="1"
                      data-pan-x="0"
                      data-pan-y="0"
                    />
                    {showCaptions && img.caption && (
                      <div className="my-gallery__imagebrowser-caption"
                      style={{ color: ImgCaptionColor,
                        backgroundColor: ImgbackgroundColor }}
                      
                      dangerouslySetInnerHTML={{ __html: img.caption }} />
                    )}
                  </div>
                );
              })}
            </div>
            
            {/* Navigation Controls */}
            {browserShowNavigation && images.length > 1 && (
              <>
                <button 
                  className="my-gallery__imagebrowser-prev"
                  aria-label="Previous image"
                  type="button"
                >
                  <span>‹</span>
                </button>
                <button 
                  className="my-gallery__imagebrowser-next"
                  aria-label="Next image"
                  type="button"
                >
                  <span>›</span>
                </button>
              </>
            )}
            
            {/* Image Counter */}
            {browserShowCounter && (
              <div className="my-gallery__imagebrowser-counter">
                <span className="current">1</span> of <span className="total">{images.length}</span>
              </div>
            )}

            {/* Zoom Controls */}
            {browserZoomEnabled && (
              <div className="my-gallery__imagebrowser-zoom-controls">
                <button 
                  className="my-gallery__imagebrowser-zoom-in"
                  aria-label="Zoom in"
                  type="button"
                  title="Zoom In"
                >
                  <span>+</span>
                </button>
                <button 
                  className="my-gallery__imagebrowser-zoom-out"
                  aria-label="Zoom out"
                  type="button"
                  title="Zoom Out"
                >
                  <span>−</span>
                </button>
                <button 
                  className="my-gallery__imagebrowser-zoom-reset"
                  aria-label="Reset zoom"
                  type="button"
                  title="Reset Zoom"
                >
                  <span>⟲</span>
                </button>
              </div>
            )}

            {/* Fullscreen Control */}
            <div className="my-gallery__imagebrowser-fullscreen-control">
              <button 
                className="my-gallery__imagebrowser-fullscreen"
                aria-label="Toggle fullscreen"
                type="button"
                title="Fullscreen"
              >
                      <span className="fullscreen-enter"><i className="fas fa-expand"></i></span>
        <span className="fullscreen-exit"><i className="fas fa-times"></i></span>
              </button>
            </div>
          </div>
          
          {/* Thumbnails */}
          {browserShowThumbnails && images.length > 1 && (
            <div className="my-gallery__imagebrowser-thumbnails">
              {images.map((img, index) => (
                <div 
                  key={img.id || index}
                  className={`my-gallery__imagebrowser-thumb ${index === 0 ? 'active' : ''}`}
                  data-image-index={index}
                  data-image-id={img.id || index}
                >
                  <img
                    src={img.sizes?.thumbnail?.url || img.url}
                    alt={img.alt || ''}
                  />
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    );

  } else if (layoutType === 'masonry') {
    return (
      <div {...blockProps}>
        <div
          className="my-gallery__masonry"
          style={{ 
            '--columns': columns, 
            '--gap': `${gap}px`,
            '--masonry-border-radius': `${masonryBorderRadius}px`,
            '--masonry-border-width': `${masonryImageBorder}px`,
            '--masonry-border-color': masonryImageBorderColor,
            '--masonry-border-style': masonryImageBorderStyle,
            display: 'grid',
            gridTemplateColumns: `repeat(${columns}, 1fr)`,
            gap: `${gap}px`
          }}
          data-layout="masonry"
          data-columns={columns}
          data-gap={gap}
          data-show-captions={showCaptions ? 'true' : 'false'}
          data-show-pagination={showPagination ? 'true' : 'false'}
          data-items-per-page={itemsPerPage}
          data-total-items={images.length}
          data-border-radius={masonryBorderRadius}
          data-border-width={masonryImageBorder}
          data-border-color={masonryImageBorderColor}
          data-border-style={masonryImageBorderStyle}
        >
          {images.map((img, index) => {
            const imageUrl = imageSize === 'custom' 
              ? img.url 
              : (img.sizes && img.sizes[imageSize] && img.sizes[imageSize].url) || img.url;
            
            const imageStyles = imageSize === 'custom' && (customWidth || customHeight) 
              ? {
                  width: customWidth ? `${customWidth}px` : 'auto',
                  height: customHeight ? `${customHeight}px` : 'auto',
                }
              : {};

            return (
              <figure 
                key={img.id || index} 
                className="my-gallery__masonry-item"
                data-image-id={img.id || index}
                data-image-index={index}
              >
                <img
                  src={imageUrl}
                  alt={img.alt || ''}
                  style={Object.keys(imageStyles).length > 0 ? imageStyles : undefined}
                  data-original-height={img.height || 'auto'}
                  data-original-width={img.width || 'auto'}
                />
                {showCaptions && img.caption && (
                  <figcaption 
                    className="my-gallery__masonry-caption" 
                    dangerouslySetInnerHTML={{ __html: img.caption }} 
                  />
                )}
              </figure>
            );
          })}
        </div>
        {showPagination && images.length > itemsPerPage && (
          <div 
            className="my-gallery__pagination"
            data-total-items={images.length}
            data-items-per-page={itemsPerPage}
          >
            {/* Pagination will be generated by JavaScript */}
          </div>
        )}
      </div>
    );
 
  } else if (layoutType === 'infinite') {
    return (
      <div {...blockProps}>

        <div className="wpg-section">
          <article className="wpg-article" style={{ '--animation-speed': `${animationSpeed}s` }}>
            <div className="wpg-div">
              <ul className="wpg-ul">
                  {images.map((img) => (
                    <li className="wpg-li" key={img.id} style={{ '--padding': `${imagepadding ?? 0}px` }}>
                      <figure className="wpg-figure">
                        <img src={imageSize === 'custom' ? img.url : img.sizes?.[imageSize]?.url || img.url} alt={img.alt}
                            style={imageSize === 'custom' ? {
                              width: customWidth ? `${customWidth}px` : 'auto',
                              height: customHeight ? `${customHeight}px` : 'auto',
                            } : undefined
                            }
                        />
                          {showCaptions && img.caption && (
                          <figcaption className="wpg-caption" 
                            style={{
                              backgroundColor: ImgbackgroundColor,
                              color: ImgCaptionColor,
                              textAlign: alignx,
                              padding: '6px 10px',
                            }} 
                          >{img.caption}</figcaption>
                        )}
                      </figure>
                    </li>
                  ))}
                </ul>
            </div>
          </article>
        </div>

      </div>
    );

  } else if (layoutType === 'swiper') {
    return (
      <div {...blockProps}>
                  <div className="swiper spg-swiper" data-autoplay={swiperautoplay}  data-swiperdelay={autoplayDelay}>
                    <div className="swiper-wrapper">
                        {images.map((img, i) => (
                            <div className="swiper-slide" key={i}>
                                <img src={imageSize === 'custom' ? img.url : img.sizes?.[imageSize]?.url || img.url} alt={img.alt}
                                    style={imageSize === 'custom' ? {
                                      width: customWidth ? `${customWidth}px` : 'auto',
                                      height: customHeight ? `${customHeight}px` : 'auto',
                                    } : undefined
                                    }
                                />
                              {showCaptions && img.caption && (
                                  <figcaption className="caption" 
                                  style={{
                                      backgroundColor: ImgbackgroundColor,
                                      color: ImgCaptionColor,
                                      textAlign: alignx,
                                      padding: '6px 10px',
                                    }} 
                                  >{img.caption}</figcaption>
                                )}
                            </div>
                        ))}
                    </div>

                    <div className="swiper-button-next"></div>
                    <div className="swiper-button-prev"></div>
                  </div>  
        </div>
    );     

  } else if (layoutType === 'custom_masonry') {
  return (
    <div {...blockProps}>
      <div
        className="masonry_img_gallery"
        style={{
          /* '--columns': `${columns}`,
          '--gap': `${gap}px`,
          '--masonry-border-radius': `${masonryBorderRadius}px`,
          '--masonry-border-width': `${masonryImageBorder}px`,
          '--masonry-border-color': masonryImageBorderColor,
          '--masonry-border-style': masonryImageBorderStyle, */
        }}
      >
        {images.map((img, i) => (
          <div key={img?.id || i} className="wpct_masonry_item">
            <img
              src={
                imageSize === 'custom'
                  ? img?.url
                  : img?.sizes?.[imageSize]?.url || img?.url
              }
              alt={img?.alt || ''}
              style={
                imageSize === 'custom'
                  ? { width: customWidth ? `${customWidth}px` : 'auto' }
                  : undefined
              }
            />
            {showCaptions && img?.caption && (
                              <figcaption className="wpct_gallery__masonry-caption">
                                {img.caption}
                              </figcaption>
            )}
          </div>
        ))}
      </div>
      {showPagination && images.length > itemsPerPage && (
          <div 
            className="my-gallery__pagination"
            data-total-items={images.length}
            data-items-per-page={itemsPerPage}
          >
            {/* Pagination will be generated by JavaScript */}
          </div>
        )}
    </div>

  );

}else if (layoutType === 'fancybox') {
    return (
       <div {...blockProps}>
      <div
        className="wpc_container"
        style={{
         gridTemplateColumns: `repeat(${columns}, 1fr)`,
        gap: `${gap}px`
        }}
      >
        {images.map((img, i) => {
          const imageUrl =
            imageSize === 'custom'
              ? img.url
              : img.sizes?.[imageSize]?.url || img.url;

          return (
            <div className="wpc_card" key={i}>
              <div className="wpc_card-image">
                <a
                  href={imageUrl}
                  data-fancybox="gallery"
                  {...(showCaptions && img?.caption
                    ? { 'data-caption': img.caption }
                    : {})}
                >
                  <img
                    src={imageUrl}
                    alt={img.alt || ''}
                    loading="lazy"
                    style={
                      imageSize === 'custom'
                        ? {
                            width: customWidth
                              ? `${customWidth}px`
                              : undefined,
                            height: customHeight
                              ? `${customHeight}px`
                              : undefined,
                          }
                        : undefined
                    }
                  />
                </a>
              </div>
            </div>
          );
        })}
      </div>
      {showPagination && images.length > itemsPerPage && (
        <div
          className="my-gallery__pagination"
          data-total-items={images.length}
          data-items-per-page={itemsPerPage}
        />
      )}
    </div>
      );


}


  // Default fallback (should not reach here)
  return <div {...blockProps}></div>;
}