import { useBlockProps } from '@wordpress/block-editor';

export default function save({ attributes }) {
  const { images = [], columns = 3, gap = 16, showCaptions = true, imageSize = 'full', customWidth = 0, customHeight = 0,
    showPagination = false, itemsPerPage = 12 } = attributes;

  // If no images, render nothing
  if (images.length === 0) {
    return null;
  }

  // Generate unique ID for this gallery instance
  const galleryId = `gallery-${Math.random().toString(36).substr(2, 9)}`;

  return (
    <div {...useBlockProps.save({ className: 'wpct-gallery' })}>
      <div
        className="wpct_gallery__grid"
        style={{ 
          '--columns': columns, 
          '--gap': `${gap}px`,
          gridTemplateColumns: `repeat(${columns}, 1fr)`,
          gap: `${gap}px`
        }}
        data-gallery-id={galleryId}
        data-show-pagination={showPagination}
        data-items-per-page={itemsPerPage}
        data-columns={columns}
      >
        {images.map((img, index) => (
          <div 
            key={img.id || index} 
            className="wpct_gallery__item"
            data-index={index}
          >
            <img
              src={
                imageSize === 'custom'
                  ? img.url
                  : img.sizes?.[imageSize]?.url || img.url
              }
              alt={img.alt || ''}
              style={
                imageSize === 'custom'
                  ? {
                      width: customWidth ? `${customWidth}px` : 'auto',
                      height: customHeight ? `${customHeight}px` : 'auto',
                    }
                  : undefined
              }
            />
            {showCaptions && img.caption && (
              <figcaption>{img.caption}</figcaption>
            )}
          </div>
        ))}
      </div>

      {/* Pagination will be handled by frontend JavaScript */}
      {showPagination && images.length > itemsPerPage && (
        <div className="wpct_gallery__pagination" data-gallery-id={galleryId}>
          {/* Pagination buttons will be generated by JS */}
        </div>
      )}
    </div>
  );
}